-- AlterTable
ALTER TABLE "Service" ADD COLUMN     "duration" INTEGER NOT NULL DEFAULT 60,
ADD COLUMN     "isMultiDay" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "maxDays" INTEGER,
ADD COLUMN     "minDays" INTEGER;
